name: Release
run-name: ${{ github.actor }} is releasing 🚀

on: workflow_dispatch

jobs:

  dev-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checking
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
    - name: Tweaking
      run: |
        rm -rf .github
        echo jan.vostry.dev >CNAME
    - name: Committing
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout --orphan master.dev
        git add .
        git commit -m Release
    - name: Pushing
      run: |
        git remote add origin.dev https://github.com/janvostry/jan.vostry.dev.git
        git push --force origin.dev
