name: Release
run-name: ${{ github.actor }} is releasing 🚀

on: workflow_dispatch

jobs:

  dev-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checking
      uses: actions/checkout@v4
    - name: Tweaking
      run: |
        echo jan.vostry.dev >CNAME
    - name: Switching
      uses: actions/checkout@v4
      with:
        repository: janvostry/jan.vostry.dev
        ref: 'master.xxx'
        token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}
    - name: Pushing
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git branch -d master.xxx
        git checkout --orphan master.xxx
        git add .
        git commit -m Release
        git push origin --force
