name: Release
run-name: User ${{ github.actor }} is releasing 🚀
on: workflow_dispatch
jobs:
  release-dev:
    environment: development
    uses: janvostry/jan.vostry/.github/workflows/template.yml@master
    with:
      tld: dev
    secrets: inherit
  release-name:
    environment: production
    uses: janvostry/jan.vostry/.github/workflows/template.yml@master
    with:
      tld: name
    secrets: inherit