name: Release
run-name: User ${{ github.actor }} is releasing 🚀
on:
- push
- workflow_dispatch
jobs:
  release-dev:
    uses: janvostry/jan.vostry/.github/workflows/template.yml@master
    with:
      environment: development
      top-level-domain: dev
    secrets: inherit
  release-name:
    uses: janvostry/jan.vostry/.github/workflows/template.yml@master
    with:
      environment: production
      top-level-domain: name
    secrets: inherit